### ISSUE TITLE
How can I run static methods?

### ISSUE THREAD

**Issue by paulocarvalho2899** [MarkusJx/node-java-bridge#4] opened 2021-12-20 10:11 UTC
I try to run static methods, but it's not accessible.

There is some way to run these methods?

console.log() - example of not static methods
![image](https://user-images.githubusercontent.com/49253207/146750362-421b0e87-180e-4634-ae94-a34341632fe1.png)

console.log() - example of static methods
![image](https://user-images.githubusercontent.com/49253207/146750465-c0b7f66e-0983-4523-a15e-46b918a6e404.png)

**Comment by MarkusJx** [comment] 2021-12-20 10:53
Could you please provide some example code to demonstrate this issue?
How did you import the class to call members on? Are the static members public?

You maybe want to take a look at the tests as those do contain some examples:
https://github.com/MarkusJx/node-java-bridge/blob/d50effbc063d923ad40f03ddaf8e44e8ba73c796/test/StringTest.ts#L8
and
https://github.com/MarkusJx/node-java-bridge/blob/d50effbc063d923ad40f03ddaf8e44e8ba73c796/test/StringTest.ts#L77

**Comment by paulocarvalho2899** [comment] 2021-12-20 14:23
```java
package main;

public class Teste {

	public String helloWorld() {
		return "Hello world :)";
	}
	
	public static String imStaticMethod() {
		return "imStaticMethod";
	}
}
```
Teste.jar
==============================

I use this code in electron app (preload.js)

```javascript
const java = require("@markusjx/java");
const { resolve } = require("path");

java.ensureJVM();

function teste() {
    try {
        java.classpath.append(resolve("assets", "jar/Teste.jar"));

        const TestClass = java.importClass("main.Teste");

        const test = new TestClass();

        // OK
        console.log(test.helloWorldSync());
        // NOT OK, only show helloWorld method
        console.log(test);
    } catch (error) {
        console.log(error);
    }
}

contextBridge.exposeInMainWorld("myAPI", {
    teste,
});
```

**Comment by MarkusJx** [comment] 2021-12-20 15:20
Yes, what you see is by design, as Java (and many other languages) discourages you to call static methods on class instances. Instead, try calling your static method on the imported class directly:
```js
// ...
function teste() {
    try {
        java.classpath.append(resolve("assets", "jar/Teste.jar"));

        const TestClass = java.importClass("main.Teste");

        const test = new TestClass();

        // OK
        console.log(test.helloWorldSync());
        // Try this (should work):
		console.log(TestClass.imStaticMethodSync());

		// Print the class instance members:
		console.log(test); // Should print a java_instance_proxy
		// Print the static class members:
		console.log(TestClass); // Should print a java_class_proxy
    } catch (error) {
        console.log(error);
    }
}
// ...
```

**Comment by paulocarvalho2899** [comment] 2021-12-21 10:39
Thanks, it works fine :)

(Maybe you should add this detail to the readme)

**Comment by MarkusJx** [comment] 2021-12-21 10:45
Yeah, I probably should. Although, thinking about this, JavaScript prohibits you in the first place to call static class members on class instances so this should be not a problem. But I'll add an example to the readme.

So I'll close this, if you have any further questions, feel free to re-open or create a new issue.
Happy Holidays! :)

**Closed by MarkusJx** 2021-12-21 10:45 UTC
Labels: documentation, enhancement
